#!/usr/bin/python3 -u

# Note that running python with the `-u` flag is required on Windows,
# in order to ensure that stdin and stdout are opened in binary, rather
# than text, mode.

from utils.messages import get_message
from utils.validation import validate_message
from utils.config import COMMAND_MAP

# Await command message
while True:
    message = get_message()
    isValid = validate_message(message)
    if isValid:
        COMMAND_MAP.get(message['cmd'])['func'](message)
